export interface CountryTheme {
  name: string;
  code: string;
  flag: string;
  greeting: string;
  landmark: string;
  landmarkType:
    | 'modern_skyline'
    | 'gothic_tower'
    | 'dome_minaret'
    | 'classical_columns'
    | 'oriental_pagoda'
    | 'natural_peaks'
    | 'ancient_pyramid'
    | 'coastal_harbor'
    | 'monument_statue';
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  glowColor: string;
  coordinates: string;
  symbols: string[];
}

/**
 * Universal Unicode Flag Generator for any ISO-2 code
 */
export function getFlagEmoji(countryCode: string): string {
  if (!countryCode || countryCode.length !== 2) return '🌐';
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map((char) => 127397 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}

/**
 * Comprehensive ISO-3166-1 alpha-2 dictionary mapping all 220+ world countries and territories
 */
export const WORLD_COUNTRY_ISO: Record<string, string> = {
  'afghanistan': 'AF',
  'albania': 'AL',
  'algeria': 'DZ',
  'andorra': 'AD',
  'angola': 'AO',
  'antigua and barbuda': 'AG',
  'argentina': 'AR',
  'armenia': 'AM',
  'australia': 'AU',
  'austria': 'AT',
  'azerbaijan': 'AZ',
  'bahamas': 'BS',
  'bahrain': 'BH',
  'bangladesh': 'BD',
  'barbados': 'BB',
  'belarus': 'BY',
  'belgium': 'BE',
  'belize': 'BZ',
  'benin': 'BJ',
  'bhutan': 'BT',
  'bolivia': 'BO',
  'bosnia and herzegovina': 'BA',
  'bosnia': 'BA',
  'botswana': 'BW',
  'brazil': 'BR',
  'brunei': 'BN',
  'bulgaria': 'BG',
  'burkina faso': 'BF',
  'burundi': 'BI',
  'cambodia': 'KH',
  'cameroon': 'CM',
  'canada': 'CA',
  'cape verde': 'CV',
  'central african republic': 'CF',
  'chad': 'TD',
  'chile': 'CL',
  'china': 'CN',
  'colombia': 'CO',
  'comoros': 'KM',
  'congo': 'CG',
  'dr congo': 'CD',
  'costa rica': 'CR',
  'croatia': 'HR',
  'cuba': 'CU',
  'cyprus': 'CY',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'denmark': 'DK',
  'djibouti': 'DJ',
  'dominica': 'DM',
  'dominican republic': 'DO',
  'ecuador': 'EC',
  'egypt': 'EG',
  'el salvador': 'SV',
  'equatorial guinea': 'GQ',
  'eritrea': 'ER',
  'estonia': 'EE',
  'eswatini': 'SZ',
  'ethiopia': 'ET',
  'fiji': 'FJ',
  'finland': 'FI',
  'france': 'FR',
  'gabon': 'GA',
  'gambia': 'GM',
  'georgia': 'GE',
  'germany': 'DE',
  'ghana': 'GH',
  'greece': 'GR',
  'grenada': 'GD',
  'guatemala': 'GT',
  'guinea': 'GN',
  'guyana': 'GY',
  'haiti': 'HT',
  'honduras': 'HN',
  'hungary': 'HU',
  'iceland': 'IS',
  'india': 'IN',
  'indonesia': 'ID',
  'iran': 'IR',
  'iraq': 'IQ',
  'ireland': 'IE',
  'israel': 'IL',
  'italy': 'IT',
  'ivory coast': 'CI',
  'jamaica': 'JM',
  'japan': 'JP',
  'jordan': 'JO',
  'kazakhstan': 'KZ',
  'kenya': 'KE',
  'kiribati': 'KI',
  'kuwait': 'KW',
  'kyrgyzstan': 'KG',
  'laos': 'LA',
  'latvia': 'LV',
  'lebanon': 'LB',
  'lesotho': 'LS',
  'liberia': 'LR',
  'libya': 'LY',
  'liechtenstein': 'LI',
  'lithuania': 'LT',
  'luxembourg': 'LU',
  'madagascar': 'MG',
  'malawi': 'MW',
  'malaysia': 'MY',
  'maldives': 'MV',
  'mali': 'ML',
  'malta': 'MT',
  'mauritania': 'MR',
  'mauritius': 'MU',
  'mexico': 'MX',
  'moldova': 'MD',
  'monaco': 'MC',
  'mongolia': 'MN',
  'montenegro': 'ME',
  'morocco': 'MA',
  'mozambique': 'MZ',
  'myanmar': 'MM',
  'namibia': 'NA',
  'nepal': 'NP',
  'netherlands': 'NL',
  'holland': 'NL',
  'new zealand': 'NZ',
  'nicaragua': 'NI',
  'niger': 'NE',
  'nigeria': 'NG',
  'north korea': 'KP',
  'north macedonia': 'MK',
  'norway': 'NO',
  'oman': 'OM',
  'pakistan': 'PK',
  'palau': 'PW',
  'palestine': 'PS',
  'panama': 'PA',
  'papua new guinea': 'PG',
  'paraguay': 'PY',
  'peru': 'PE',
  'philippines': 'PH',
  'poland': 'PL',
  'portugal': 'PT',
  'qatar': 'QA',
  'romania': 'RO',
  'russia': 'RU',
  'rwanda': 'RW',
  'saint kitts and nevis': 'KN',
  'saint lucia': 'LC',
  'samoa': 'WS',
  'san marino': 'SM',
  'saudi arabia': 'SA',
  'scotland': 'GB',
  'senegal': 'SN',
  'serbia': 'RS',
  'seychelles': 'SC',
  'sierra leone': 'SL',
  'singapore': 'SG',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'somalia': 'SO',
  'south africa': 'ZA',
  'south korea': 'KR',
  'korea': 'KR',
  'south sudan': 'SS',
  'spain': 'ES',
  'sri lanka': 'LK',
  'sudan': 'SD',
  'suriname': 'SR',
  'sweden': 'SE',
  'switzerland': 'CH',
  'syria': 'SY',
  'taiwan': 'TW',
  'tajikistan': 'TJ',
  'tanzania': 'TZ',
  'thailand': 'TH',
  'timor-leste': 'TL',
  'togo': 'TG',
  'tonga': 'TO',
  'trinidad and tobago': 'TT',
  'trinidad': 'TT',
  'tunisia': 'TN',
  'turkey': 'TR',
  'turkmenistan': 'TM',
  'tuvalu': 'TV',
  'uganda': 'UG',
  'ukraine': 'UA',
  'united arab emirates': 'AE',
  'uae': 'AE',
  'united kingdom': 'GB',
  'uk': 'GB',
  'britain': 'GB',
  'england': 'GB',
  'wales': 'GB',
  'united states': 'US',
  'usa': 'US',
  'uruguay': 'UY',
  'uzbekistan': 'UZ',
  'vanuatu': 'VU',
  'vatican city': 'VA',
  'venezuela': 'VE',
  'vietnam': 'VN',
  'yemen': 'YE',
  'zambia': 'ZM',
  'zimbabwe': 'ZW',
};

/**
 * Detailed 2.5D visual themes for flagship world countries
 */
export const COUNTRY_DATABASE: Record<string, CountryTheme> = {
  'united states': {
    name: 'United States',
    code: 'USA',
    flag: '🇺🇸',
    greeting: 'Hey there / Howdy!',
    landmark: 'Empire State & Liberty Torch',
    landmarkType: 'modern_skyline',
    primaryColor: '#3b82f6',
    secondaryColor: '#ef4444',
    accentColor: '#f8fafc',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    coordinates: '38.8951° N, 77.0364° W',
    symbols: ['🗽', '🦅', '⭐', '🏙️', '🏈'],
  },
  'united kingdom': {
    name: 'United Kingdom',
    code: 'GBR',
    flag: '🇬🇧',
    greeting: 'Cheers, mate! / Right then',
    landmark: 'Big Ben & London Spire',
    landmarkType: 'gothic_tower',
    primaryColor: '#1d4ed8',
    secondaryColor: '#dc2626',
    accentColor: '#ffffff',
    glowColor: 'rgba(29, 78, 216, 0.4)',
    coordinates: '51.5074° N, 0.1278° W',
    symbols: ['🕰️', '👑', '🫖', '🚌', '🌧️'],
  },
  'australia': {
    name: 'Australia',
    code: 'AUS',
    flag: '🇦🇺',
    greeting: "G'day, mate! / No worries",
    landmark: 'Sydney Opera & Harbour Wave',
    landmarkType: 'coastal_harbor',
    primaryColor: '#0284c7',
    secondaryColor: '#f59e0b',
    accentColor: '#10b981',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    coordinates: '33.8688° S, 151.2093° E',
    symbols: ['🦘', '🌊', '☀️', '🏄', '🐨'],
  },
  'canada': {
    name: 'Canada',
    code: 'CAN',
    flag: '🇨🇦',
    greeting: 'Hey, how’s it going, eh?',
    landmark: 'CN Tower & Rocky Mountain Peaks',
    landmarkType: 'natural_peaks',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '45.4215° N, 75.6972° W',
    symbols: ['🍁', '🏔️', '🏒', '❄️', '🌲'],
  },
  'india': {
    name: 'India',
    code: 'IND',
    flag: '🇮🇳',
    greeting: 'Namaste / Vanakkam',
    landmark: 'Taj Mahal Dome & Minarets',
    landmarkType: 'dome_minaret',
    primaryColor: '#f97316',
    secondaryColor: '#16a34a',
    accentColor: '#1e3a8a',
    glowColor: 'rgba(249, 115, 22, 0.4)',
    coordinates: '28.6139° N, 77.2090° E',
    symbols: ['🪷', '🦚', '☸️', '🕌', '🎶'],
  },
  'pakistan': {
    name: 'Pakistan',
    code: 'PAK',
    flag: '🇵🇰',
    greeting: 'Assalam-o-Alaikum',
    landmark: 'Minar-e-Pakistan & Badshahi Dome',
    landmarkType: 'dome_minaret',
    primaryColor: '#059669',
    secondaryColor: '#ffffff',
    accentColor: '#10b981',
    glowColor: 'rgba(5, 150, 105, 0.4)',
    coordinates: '33.6844° N, 73.0479° E',
    symbols: ['🌙', '⭐', '🕌', '🏔️', '🍵'],
  },
  'nigeria': {
    name: 'Nigeria',
    code: 'NGA',
    flag: '🇳🇬',
    greeting: 'How far? / Bawo ni / Kedu',
    landmark: 'Zuma Rock & Emerald Monolith',
    landmarkType: 'natural_peaks',
    primaryColor: '#16a34a',
    secondaryColor: '#ffffff',
    accentColor: '#15803d',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '9.0765° N, 7.3986° E',
    symbols: ['🦅', '🪘', '🌿', '⚡', '👑'],
  },
  'germany': {
    name: 'Germany',
    code: 'DEU',
    flag: '🇩🇪',
    greeting: 'Hallo / Guten Tag!',
    landmark: 'Brandenburg Gate Columns',
    landmarkType: 'classical_columns',
    primaryColor: '#eab308',
    secondaryColor: '#dc2626',
    accentColor: '#0f172a',
    glowColor: 'rgba(234, 179, 8, 0.4)',
    coordinates: '52.5200° N, 13.4050° E',
    symbols: ['🦅', '⚙️', '🏰', '🥨', '🍺'],
  },
  'france': {
    name: 'France',
    code: 'FRA',
    flag: '🇫🇷',
    greeting: 'Bonjour / Salut!',
    landmark: 'Eiffel Tower Beacon',
    landmarkType: 'gothic_tower',
    primaryColor: '#2563eb',
    secondaryColor: '#ef4444',
    accentColor: '#ffffff',
    glowColor: 'rgba(37, 99, 235, 0.4)',
    coordinates: '48.8566° N, 2.3522° E',
    symbols: ['🗼', '🥖', '🍷', '🎨', '✨'],
  },
  'ireland': {
    name: 'Ireland',
    code: 'IRL',
    flag: '🇮🇪',
    greeting: "What's the craic? / Dia duit",
    landmark: 'Cliffs of Moher & Emerald Spire',
    landmarkType: 'natural_peaks',
    primaryColor: '#16a34a',
    secondaryColor: '#f97316',
    accentColor: '#ffffff',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '53.3498° N, 6.2603° W',
    symbols: ['☘️', '🌈', '🎻', '🍺', '🏰'],
  },
  'japan': {
    name: 'Japan',
    code: 'JPN',
    flag: '🇯🇵',
    greeting: 'Konnichiwa / やあ',
    landmark: 'Mount Fuji & Torii Pagoda',
    landmarkType: 'oriental_pagoda',
    primaryColor: '#e11d48',
    secondaryColor: '#ffffff',
    accentColor: '#fb7185',
    glowColor: 'rgba(225, 29, 72, 0.4)',
    coordinates: '35.6762° N, 139.6503° E',
    symbols: ['⛩️', '🌸', '🗻', '🍵', '🏯'],
  },
  'china': {
    name: 'China',
    code: 'CHN',
    flag: '🇨🇳',
    greeting: 'Nǐ hǎo / 你好',
    landmark: 'Great Wall & Imperial Pagoda',
    landmarkType: 'oriental_pagoda',
    primaryColor: '#dc2626',
    secondaryColor: '#eab308',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '39.9042° N, 116.4074° E',
    symbols: ['🏮', '🐉', '🎋', '🏯', '✨'],
  },
  'south africa': {
    name: 'South Africa',
    code: 'ZAF',
    flag: '🇿🇦',
    greeting: 'Howzit! / Sawubona',
    landmark: 'Table Mountain Plateau',
    landmarkType: 'natural_peaks',
    primaryColor: '#059669',
    secondaryColor: '#f59e0b',
    accentColor: '#2563eb',
    glowColor: 'rgba(5, 150, 105, 0.4)',
    coordinates: '33.9249° S, 18.4241° E',
    symbols: ['🦁', '🏔️', '🌺', '🏉', '☀️'],
  },
  'new zealand': {
    name: 'New Zealand',
    code: 'NZL',
    flag: '🇳🇿',
    greeting: 'Kia Ora / Sweet as, bro!',
    landmark: 'Southern Alps & Sky Tower',
    landmarkType: 'natural_peaks',
    primaryColor: '#0284c7',
    secondaryColor: '#dc2626',
    accentColor: '#1e293b',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    coordinates: '41.2865° S, 174.7762° E',
    symbols: ['🥝', '🌿', '🏔️', '🏉', '🌊'],
  },
  'italy': {
    name: 'Italy',
    code: 'ITA',
    flag: '🇮🇹',
    greeting: 'Ciao! / Buongiorno',
    landmark: 'Colosseum Arches & Tuscan Villa',
    landmarkType: 'classical_columns',
    primaryColor: '#16a34a',
    secondaryColor: '#dc2626',
    accentColor: '#ffffff',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '41.9028° N, 12.4964° E',
    symbols: ['🏛️', '🍕', '☕', '🎭', '☀️'],
  },
  'spain': {
    name: 'Spain',
    code: 'ESP',
    flag: '🇪🇸',
    greeting: '¡Hola! / ¿Qué tal?',
    landmark: 'Sagrada Spire & Plaza Colonnade',
    landmarkType: 'gothic_tower',
    primaryColor: '#eab308',
    secondaryColor: '#dc2626',
    accentColor: '#f97316',
    glowColor: 'rgba(234, 179, 8, 0.4)',
    coordinates: '40.4168° N, 3.7038° W',
    symbols: ['💃', '☀️', '🏰', '🎸', '🍊'],
  },
  'mexico': {
    name: 'Mexico',
    code: 'MEX',
    flag: '🇲🇽',
    greeting: '¡Qué onda! / ¿Qué pasó?',
    landmark: 'Chichen Itza Pyramid Steps',
    landmarkType: 'ancient_pyramid',
    primaryColor: '#16a34a',
    secondaryColor: '#dc2626',
    accentColor: '#ffffff',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '19.4326° N, 99.1332° W',
    symbols: ['🌮', '🌵', '☀️', '🎺', '💀'],
  },
  'brazil': {
    name: 'Brazil',
    code: 'BRA',
    flag: '🇧🇷',
    greeting: 'Tudo bem! / E aí, beleza?',
    landmark: 'Christ the Redeemer & Sugarloaf',
    landmarkType: 'monument_statue',
    primaryColor: '#16a34a',
    secondaryColor: '#eab308',
    accentColor: '#2563eb',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '15.7975° S, 47.8919° W',
    symbols: ['⚽', '🌴', '🦜', '🎉', '🏖️'],
  },
  'russia': {
    name: 'Russia',
    code: 'RUS',
    flag: '🇷🇺',
    greeting: 'Privet! / Zdravstvuyte',
    landmark: "St. Basil's Domes & Spire",
    landmarkType: 'dome_minaret',
    primaryColor: '#dc2626',
    secondaryColor: '#2563eb',
    accentColor: '#ffffff',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '55.7558° N, 37.6173° E',
    symbols: ['🪆', '❄️', '🐻', '🏰', '✨'],
  },
  'jamaica': {
    name: 'Jamaica',
    code: 'JAM',
    flag: '🇯🇲',
    greeting: 'Wah gwaan! / Irie mon',
    landmark: 'Blue Mountain & Caribbean Coast',
    landmarkType: 'coastal_harbor',
    primaryColor: '#16a34a',
    secondaryColor: '#eab308',
    accentColor: '#0f172a',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '17.9714° N, 76.7936° W',
    symbols: ['🌴', '☀️', '🎶', '🌊', '⚡'],
  },
  'sweden': {
    name: 'Sweden',
    code: 'SWE',
    flag: '🇸🇪',
    greeting: 'Hej / Hallå!',
    landmark: 'Stockholm Royal Waterfront',
    landmarkType: 'natural_peaks',
    primaryColor: '#0284c7',
    secondaryColor: '#eab308',
    accentColor: '#ffffff',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    coordinates: '59.3293° N, 18.0686° E',
    symbols: ['🦌', '❄️', '🌲', '⛵', '✨'],
  },
  'netherlands': {
    name: 'Netherlands',
    code: 'NLD',
    flag: '🇳🇱',
    greeting: 'Hallo / Goedendag!',
    landmark: 'Amsterdam Canal Gables & Windmills',
    landmarkType: 'gothic_tower',
    primaryColor: '#ea580c',
    secondaryColor: '#2563eb',
    accentColor: '#ffffff',
    glowColor: 'rgba(234, 88, 12, 0.4)',
    coordinates: '52.3676° N, 4.9041° E',
    symbols: ['🌷', '🚲', '🧀', '🛶', '🦁'],
  },
  'philippines': {
    name: 'Philippines',
    code: 'PHL',
    flag: '🇵🇭',
    greeting: 'Mabuhay / Kumusta!',
    landmark: 'Mayon Volcano & Manila Bay Harbor',
    landmarkType: 'coastal_harbor',
    primaryColor: '#2563eb',
    secondaryColor: '#dc2626',
    accentColor: '#eab308',
    glowColor: 'rgba(37, 99, 235, 0.4)',
    coordinates: '14.5995° N, 120.9842° E',
    symbols: ['☀️', '🌴', '🌺', '🇵🇭', '🌊'],
  },
  'argentina': {
    name: 'Argentina',
    code: 'ARG',
    flag: '🇦🇷',
    greeting: '¡Hola che / Buen día!',
    landmark: 'Obelisco & Plaza de Mayo Colonnade',
    landmarkType: 'classical_columns',
    primaryColor: '#0284c7',
    secondaryColor: '#ffffff',
    accentColor: '#eab308',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    coordinates: '34.6037° S, 58.3816° W',
    symbols: ['☀️', '⚽', '🥩', '💃', '🏔️'],
  },
  'egypt': {
    name: 'Egypt',
    code: 'EGY',
    flag: '🇪🇬',
    greeting: 'Ahlan wa Sahlan / Marhaban!',
    landmark: 'Great Pyramids of Giza & Nile Towers',
    landmarkType: 'ancient_pyramid',
    primaryColor: '#dc2626',
    secondaryColor: '#eab308',
    accentColor: '#0f172a',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '30.0444° N, 31.2357° E',
    symbols: ['🔺', '🦅', '☀️', '🏺', '✨'],
  },
  'south korea': {
    name: 'South Korea',
    code: 'KOR',
    flag: '🇰🇷',
    greeting: 'Annyeonghaseyo / 안녕하세요!',
    landmark: 'N Seoul Tower & Gyeongbokgung Spire',
    landmarkType: 'oriental_pagoda',
    primaryColor: '#dc2626',
    secondaryColor: '#2563eb',
    accentColor: '#ffffff',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '37.5665° N, 126.9780° E',
    symbols: ['☯️', '🌸', '🏙️', '🎤', '✨'],
  },
  'poland': {
    name: 'Poland',
    code: 'POL',
    flag: '🇵🇱',
    greeting: 'Cześć / Dzień dobry!',
    landmark: 'Wawel Castle & Warsaw Spire',
    landmarkType: 'gothic_tower',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#991b1b',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '52.2297° N, 21.0122° E',
    symbols: ['🦅', '🏰', '🌲', '🥟', '✨'],
  },
  'portugal': {
    name: 'Portugal',
    code: 'PRT',
    flag: '🇵🇹',
    greeting: 'Olá / Bom dia!',
    landmark: 'Belém Tower & Atlantic Coast',
    landmarkType: 'coastal_harbor',
    primaryColor: '#16a34a',
    secondaryColor: '#dc2626',
    accentColor: '#eab308',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '38.7223° N, 9.1393° W',
    symbols: ['🌊', '⛵', '🏰', '🍷', '☀️'],
  },
  'greece': {
    name: 'Greece',
    code: 'GRC',
    flag: '🇬🇷',
    greeting: 'Geia sas / Kalimera!',
    landmark: 'Parthenon Colonnade & Aegean Vista',
    landmarkType: 'classical_columns',
    primaryColor: '#0284c7',
    secondaryColor: '#ffffff',
    accentColor: '#0369a1',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    coordinates: '37.9838° N, 23.7275° E',
    symbols: ['🏛️', '🌊', '☀️', '🫒', '🏺'],
  },
  'colombia': {
    name: 'Colombia',
    code: 'COL',
    flag: '🇨🇴',
    greeting: '¡Hola! / ¿Qué más, parce?',
    landmark: 'Monserrate Sanctuary & Andes Skyline',
    landmarkType: 'natural_peaks',
    primaryColor: '#eab308',
    secondaryColor: '#2563eb',
    accentColor: '#dc2626',
    glowColor: 'rgba(234, 179, 8, 0.4)',
    coordinates: '4.7110° N, 74.0721° W',
    symbols: ['☕', '🦜', '🌺', '🏔️', '💃'],
  },
  'singapore': {
    name: 'Singapore',
    code: 'SGP',
    flag: '🇸🇬',
    greeting: 'Hello / Ni Hao / Vanakkam!',
    landmark: 'Marina Bay Sands & Supertree Grove',
    landmarkType: 'modern_skyline',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#38bdf8',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '1.3521° N, 103.8198° E',
    symbols: ['🦁', '🏙️', '🌺', '✨', '⚡'],
  },
  'turkey': {
    name: 'Turkey',
    code: 'TUR',
    flag: '🇹🇷',
    greeting: 'Merhaba / Günaydın!',
    landmark: 'Hagia Sophia Domes & Bosphorus Bridge',
    landmarkType: 'dome_minaret',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '39.9334° N, 32.8597° E',
    symbols: ['🌙', '⭐', '🕌', '☕', '🧿'],
  },
  'saudi arabia': {
    name: 'Saudi Arabia',
    code: 'SAU',
    flag: '🇸🇦',
    greeting: 'Marhaban / Salam Alaikum!',
    landmark: 'Kingdom Centre Tower & Desert Minarets',
    landmarkType: 'modern_skyline',
    primaryColor: '#16a34a',
    secondaryColor: '#ffffff',
    accentColor: '#15803d',
    glowColor: 'rgba(22, 163, 74, 0.4)',
    coordinates: '24.7136° N, 46.6753° E',
    symbols: ['🌴', '⚔️', '🕌', '🐪', '✨'],
  },
  'vietnam': {
    name: 'Vietnam',
    code: 'VNM',
    flag: '🇻🇳',
    greeting: 'Xin chào!',
    landmark: 'Ha Long Bay Karsts & Hanoi Spire',
    landmarkType: 'coastal_harbor',
    primaryColor: '#dc2626',
    secondaryColor: '#eab308',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '21.0285° N, 105.8542° E',
    symbols: ['⭐', '🍜', '🎋', '🐉', '🌾'],
  },
  'thailand': {
    name: 'Thailand',
    code: 'THA',
    flag: '🇹🇭',
    greeting: 'Sawasdee khrap / ka!',
    landmark: 'Grand Palace Golden Stupa & Chao Phraya',
    landmarkType: 'oriental_pagoda',
    primaryColor: '#2563eb',
    secondaryColor: '#dc2626',
    accentColor: '#eab308',
    glowColor: 'rgba(37, 99, 235, 0.4)',
    coordinates: '13.7563° N, 100.5018° E',
    symbols: ['🐘', '🛕', '🌺', '☀️', '✨'],
  },
  'kenya': {
    name: 'Kenya',
    code: 'KEN',
    flag: '🇰🇪',
    greeting: 'Jambo / Hujambo!',
    landmark: 'Mount Kenya Peak & Great Rift Valley',
    landmarkType: 'natural_peaks',
    primaryColor: '#dc2626',
    secondaryColor: '#16a34a',
    accentColor: '#000000',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '1.2921° S, 36.8219° E',
    symbols: ['🦁', '🛡️', '🏔️', '🏃', '☀️'],
  },
  'ghana': {
    name: 'Ghana',
    code: 'GHA',
    flag: '🇬🇭',
    greeting: 'Akwaaba / How far!',
    landmark: 'Black Star Gate & Atlantic Coast',
    landmarkType: 'monument_statue',
    primaryColor: '#dc2626',
    secondaryColor: '#eab308',
    accentColor: '#16a34a',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '5.6037° N, 0.1870° W',
    symbols: ['⭐', '🪘', '🍫', '👑', '☀️'],
  },
  'switzerland': {
    name: 'Switzerland',
    code: 'CHE',
    flag: '🇨🇭',
    greeting: 'Grüezi / Bonjour / Ciao!',
    landmark: 'Matterhorn Alpine Pinnacle',
    landmarkType: 'natural_peaks',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '46.9480° N, 7.4474° E',
    symbols: ['🏔️', '❄️', '🧀', '🍫', '🕰️'],
  },
  'norway': {
    name: 'Norway',
    code: 'NOR',
    flag: '🇳🇴',
    greeting: 'Hei / Hallo!',
    landmark: 'Geirangerfjord & Holmenkollen Spire',
    landmarkType: 'natural_peaks',
    primaryColor: '#dc2626',
    secondaryColor: '#1e3a8a',
    accentColor: '#ffffff',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '59.9139° N, 10.7522° E',
    symbols: ['🏔️', '❄️', '🌲', '⛵', '👑'],
  },
  'denmark': {
    name: 'Denmark',
    code: 'DNK',
    flag: '🇩🇰',
    greeting: 'Hej / Goddag!',
    landmark: 'Nyhavn Harbor & Little Mermaid Coast',
    landmarkType: 'coastal_harbor',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '55.6761° N, 12.5683° E',
    symbols: ['🚲', '👑', '⛵', '🦢', '✨'],
  },
  'austria': {
    name: 'Austria',
    code: 'AUT',
    flag: '🇦🇹',
    greeting: 'Servus / Grüß Gott!',
    landmark: "St. Stephen's Gothic Cathedral & Alps",
    landmarkType: 'gothic_tower',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '48.2082° N, 16.3738° E',
    symbols: ['🎻', '🏔️', '🏰', '🍰', '🦅'],
  },
  'chile': {
    name: 'Chile',
    code: 'CHL',
    flag: '🇨🇱',
    greeting: '¡Hola po / Buena onda!',
    landmark: 'Gran Torre Santiago & Andes Spine',
    landmarkType: 'natural_peaks',
    primaryColor: '#dc2626',
    secondaryColor: '#2563eb',
    accentColor: '#ffffff',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '33.4489° S, 70.6693° W',
    symbols: ['⭐', '🏔️', '🍷', '🌊', '🌵'],
  },
  'indonesia': {
    name: 'Indonesia',
    code: 'IDN',
    flag: '🇮🇩',
    greeting: 'Halo / Selamat pagi!',
    landmark: 'Borobudur Stupas & Bali Sea Coast',
    landmarkType: 'oriental_pagoda',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    accentColor: '#b91c1c',
    glowColor: 'rgba(220, 38, 38, 0.4)',
    coordinates: '6.2088° S, 106.8456° E',
    symbols: ['🌋', '🌴', '🛕', '🌺', '🌊'],
  },
  'malaysia': {
    name: 'Malaysia',
    code: 'MYS',
    flag: '🇲🇾',
    greeting: 'Selamat / Hello lah!',
    landmark: 'Petronas Twin Towers & Skybridge',
    landmarkType: 'modern_skyline',
    primaryColor: '#2563eb',
    secondaryColor: '#dc2626',
    accentColor: '#eab308',
    glowColor: 'rgba(37, 99, 235, 0.4)',
    coordinates: '3.1390° N, 101.6869° E',
    symbols: ['🏙️', '🌴', '🐯', '🌙', '⭐'],
  },
};

/**
 * Universal theme resolver for EVERY country in the world
 */
export function getCountryTheme(countryName: string): CountryTheme {
  const raw = countryName.trim();
  const normalized = raw.toLowerCase();

  // 1. Direct match in curated themes
  if (COUNTRY_DATABASE[normalized]) {
    return COUNTRY_DATABASE[normalized];
  }

  // 2. Partial match in curated themes
  for (const [key, val] of Object.entries(COUNTRY_DATABASE)) {
    if (normalized === key || normalized.includes(key) || key.includes(normalized)) {
      return val;
    }
  }

  // 3. Check world country ISO directory
  let isoCode = WORLD_COUNTRY_ISO[normalized];
  if (!isoCode) {
    for (const [countryKey, code] of Object.entries(WORLD_COUNTRY_ISO)) {
      if (normalized.includes(countryKey) || countryKey.includes(normalized)) {
        isoCode = code;
        break;
      }
    }
  }

  // Calculate deterministic theme properties using string hashing
  const hash = hashString(raw);
  const flag = isoCode ? getFlagEmoji(isoCode) : '🌐';
  const code = isoCode ? (isoCode.length === 2 ? `${isoCode}A` : isoCode) : raw.slice(0, 3).toUpperCase();

  const colorPalettes = [
    { primary: '#6366f1', secondary: '#ec4899', accent: '#38bdf8' },
    { primary: '#06b6d4', secondary: '#10b981', accent: '#f59e0b' },
    { primary: '#8b5cf6', secondary: '#f43f5e', accent: '#fbbf24' },
    { primary: '#14b8a6', secondary: '#3b82f6', accent: '#f97316' },
    { primary: '#d946ef', secondary: '#8b5cf6', accent: '#06b6d4' },
    { primary: '#f97316', secondary: '#0284c7', accent: '#e11d48' },
    { primary: '#10b981', secondary: '#f59e0b', accent: '#3b82f6' },
    { primary: '#ef4444', secondary: '#3b82f6', accent: '#ffffff' },
  ];
  const palette = colorPalettes[Math.abs(hash) % colorPalettes.length];

  const landmarkTypes: CountryTheme['landmarkType'][] = [
    'modern_skyline',
    'gothic_tower',
    'dome_minaret',
    'classical_columns',
    'oriental_pagoda',
    'natural_peaks',
    'ancient_pyramid',
    'coastal_harbor',
    'monument_statue',
  ];
  const lType = landmarkTypes[Math.abs(hash >> 3) % landmarkTypes.length];

  // Capitalize properly
  const formattedName = raw
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');

  return {
    name: formattedName,
    code,
    flag,
    greeting: `Greetings from ${formattedName}!`,
    landmark: `${formattedName} National Monument & Spire`,
    landmarkType: lType,
    primaryColor: palette.primary,
    secondaryColor: palette.secondary,
    accentColor: palette.accent,
    glowColor: `${palette.primary}66`,
    coordinates: `${Math.abs((hash % 70) + 10)}° N, ${Math.abs(((hash >> 4) % 140) + 20)}° E`,
    symbols: ['🏛️', '🌍', '🎙️', '✨', '📡'],
  };
}

function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return hash;
}
